### ISSUE TITLE
NumscaRange operator ":>" doesn't work

### ISSUE THREAD

**Issue by filipeclduarte** [botkop/numsca#12]
The operator of NumscaRange didn't work for me. The scala compiler couldn't understand it and asked if I was targeting the ">>>" operator.

**Comment by koen-dejonghe** [comment]
can you provide code for this error?

**Comment by filipeclduarte** [comment]
``` 
import botkop.{numsca => ns}
import ns.Tensor

val ta: Tensor = ns.arange(10)
val a0 = ta.copy().reshape(10, 1)

a0(1 :> )
```
got this:
scala> a0(1 :> )
            ^
       error: value :> is not a member of Int
       did you mean >>>?

`val a2 = a0(0 :> -1)`
                     ^
       error: value :> is not a member of Int
       did you mean >>>?

**Comment by koen-dejonghe** [comment]
can you try the following:

```
import botkop.{numsca => ns}
import ns._
import scala.language.postfixOps

val ta: Tensor = ns.arange(10)
val a0 = ta.copy().reshape(10, 1)

a0(1 :> )
```

**Comment by filipeclduarte** [comment]
This example works fine.
