### ISSUE TITLE
how to convert Array[Double] or List[Double] to Tensor?

### ISSUE THREAD

**Issue by chenhaoenen** [botkop/numsca#13]
Thank you so much for this repository, But how to convert  Array[Double] or List[Double] to Tensor directly?

**Comment by chenhaoenen** [comment]
Another question, How do you translate 2d matrix directly into tensor?  for example

a = Array(
                Array(1,2,3,4),
                Array(5,6,7,8)
              )

**Comment by koen-dejonghe** [comment]
You can do this:
```
scala> val a = Array(1.2, 2.3)
a: Array[Double] = Array(1.2, 2.3)

scala> Tensor(a)
res11: botkop.numsca.Tensor = [1.20,  2.30]
```
(you need an array of Doubles in this case)

```
scala> Tensor(1, 2, 3, 4, 5, 6, 7, 8).reshape(2, 4)
res1: botkop.numsca.Tensor =
[[1.00,  2.00,  3.00,  4.00],
 [5.00,  6.00,  7.00,  8.00]]
 ```
Converting nested arrays is not implemented.

**Comment by chenhaoenen** [comment]
thanks for your reply
