### ISSUE TITLE
numpy api coverage

### ISSUE THREAD

**Issue by GraydenH** [botkop/numsca#5]
Does this library not support the numpy functions numpy .cumsum, numpy .atleast_2d, numpy.empty or numpy .searchsorted? What version of numpy is this library covering and how much of the api is covered?

**Comment by koen-dejonghe** [comment]
Hi, the functions you mention are not implemented, for the simple reason that I never had a use for them. As I mention in the README, this is not an exhaustive implementation of numpy. I add things as I go. Nor does it adhere to a certain version of numpy. You are of course welcome to contribute. Thank you.
